# Copyright (c) 2021 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

ARG EII_VERSION
FROM ia_config_agent:${EII_VERSION}
WORKDIR /EII/etcd

ENV http_proxy http://proxy.iind.intel.com:911
ENV https_proxy http://proxy.iind.intel.com:911

# Setting python runtime
RUN apt-get update && \
    apt-get install -y --no-install-recommends python3-distutils python3-minimal

RUN apt-get update && \
    apt-get install -y --no-install-recommends software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y --no-install-recommends python3-pip && \
    python3 -m pip install -U pip && \
    ln -sf /usr/bin/pip /usr/bin/pip3

COPY --from=ia_config_agent:3.0 /EII/etcd /EII/etcd
WORKDIR /EII/etcd

ENV PYTHONPATH $PYTHONPATH:/EII/etcd/.local/lib/python3.8/site-packages:/EII/etcd

COPY etcd_provision.py ./etcd_provision.py
HEALTHCHECK NONE

ENTRYPOINT ["python3", "etcd_provision.py"]

